Add pixpress
valora-inc/dapp-list pull request #222
Opened 2022-07-25 16:39 UTC by devarellin

> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

2022-07-29 18:36 UTC, MuckT commented
Main needs to be merged into this branch to grab the latest changes.
1. I am able to connect to the app just fine; however, when attempting swap I am getting 'All assets needs to be approve before swap'. No prompt is being served in Valora to approve the assets and because of this I am unable to swap.
2. One nitpick is the mobile UI leaves a lot of whitespace to the right on the swap columns.
<img src="https://user-images.githubusercontent.com/26950305/181823232-689af3f1-ce29-4a0d-af25-b0eed63d2961.png" width="50%" height="50%" />

2022-07-30 17:47 UTC, devarellin commented
@MuckT Hi, clicking the lock icon can approve the asset.

But it seems not that intuitive. Maybe I should modify it to a button with approve text?

2022-07-31 04:46 UTC, devarellin commented
Hi we've updated the approval button to text, this would be more intuitive.
![update](https://user-images.githubusercontent.com/87940921/182010543-1c597ab1-8dba-4a1b-a7e0-3f3221de8e1e.png)

2022-07-31 10:39 UTC, devarellin commented
Thanks for suggestion! this is because it's only one asset, sometimes people swap multiple assets in the same transaction and the rest space gets filled

> One nitpick is the mobile UI leaves a lot of whitespace to the right on the swap columns.

2022-08-05 16:21 UTC, devarellin commented
Hi @MuckT we've updated our connector, now every transaction will lead to Valora confirmation prompt.

2022-08-11 00:35 UTC, MuckT commented
@devarellin - please swap the names to match icons.

#### Screenshot
<img src="https://user-images.githubusercontent.com/26950305/184045605-abf0c1c2-3f51-4012-b507-c2e87af3d2b5.png" width="50%" height="auto" />

2022-08-11 09:20 UTC, devarellin commented
Oops, fixed @MuckT please have a look

2022-08-15 17:21 UTC, MuckT requested changes
Spelling fix.

2022-08-15 17:21 UTC, MuckT commented on locales/base.json
> +    "pixpress": "Swap any amount of any cryto assets with others peer-to-peer and earn rewards"
Spelling of crypto.

2022-08-21 03:27 UTC, merged